version: '3'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /projects/schulung/nestjs/code/shopping-list/docker/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
